### ISSUE TITLE
Clamby detect all the files as virus and not safe!

### ISSUE THREAD

**Issue by AstmDesign** [kobaltz/clamby#43]
Guys, I'm using `Rails 4` with Ruby version `2.2.10` , I added the `gem 'clamby'` to my Gemfile 
then   installed the gem by used the command `bundle install`
and added the below configurations to my file `/config/initializers/clamby.rb` :
```
Clamby.configure({
  :check => false,
  :daemonize => true,
  :config_file => nil,
  :error_clamscan_missing => false,
  :error_clamscan_client_error => false,
  :error_file_missing => false,
  :error_file_virus => false,
  :fdpass => true,
  :stream => true,
  :output_level => 'medium', # one of 'off', 'low', 'medium', 'high'
  :executable_path_clamscan => 'clamscan',
  :executable_path_clamdscan => 'clamdscan',
  :executable_path_freshclam => 'freshclam'
})
```

but actually my application is dockerized so I defined clamav in my `docker-compose.yml` file as service

```
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    environment:
      MODE: av
    ulimits:
      stack: 1048576
    volumes:
      - conf:/etc/clamav
      - data:/var/lib/clamav

  freshclam:
    image: aschepis/freshclam
    environment:
      MODE: updater
    volumes:
      - conf:/etc/clamav
      - data:/var/lib/clamav

  clamav_milter:
    image: bastienf/clamav-milter
    environment:
      MODE: milter
    container_name: clamav_milter_1
    volumes:
      - conf:/etc/clamav

  clamav_daemon:
    image: oh22/clamav-daemon
    container_name: clamav_daemon_1
    volumes:
      - conf:/etc/clamav
app:
  links:
      - clamav:clamav
  depends_on:
      - clamav
      - freshclam
      - clamav_milter
      - clamav_daemon
volumes:
  conf:
  data:
```
but I tested the gem through `rails c` and found it catch any file as virus and not safe file!!

```
Clamby.safe?("#{Rails.root}/public/images/astm.txt")
=> false
Clamby.virus?("#{Rails.root}/public/images/astm.txt")
=> true
```

Also I tried all the configurations options but still facing the same case!
what I miss?!!

**Comment by AstmDesign** [comment]
I solved it by using the below steps and commands: 
I added the `gem 'clamby' `    to my Gemfile then installed the gem by used the command `bundle install`
then I added  the below configurations to my file `/config/initializers/clamby.rb`
```
# frozen_string_literal: true
Clamby.configure({
  :check => false,
  :daemonize => true,
  :config_file => '/app_path/config/clamd.conf',
  :error_clamscan_missing => false,
  :error_clamscan_client_error => false,
  :error_file_missing => false,
  :error_file_virus => false,
  :fdpass => true,
  :stream => true,
  :output_level => 'medium', # one of 'off', 'low', 'medium', 'high'
  :datadir=>nil,
  :executable_path_clamscan => 'clamscan',
  :executable_path_clamdscan => 'clamdscan',
  :executable_path_freshclam => 'freshclam'
})
```
then add the inside the file `config/clamd.conf`
```
TCPSocket 3310
TCPAddr clamav
```

And I defined clamav as service in my `docker-compose.yml`:
```
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    environment:
      MODE: av
    ulimits:
      stack: 1048576
    volumes:
      - conf:/etc/clamav
      - data:/var/lib/clamav
  app:
    depends_on:
      - clamav
volumes:
  conf:
  data:
```
The you need to install the Clamav also on the same app container by adding the below commands in the `Dockerfile`:
```
RUN apt-get update -qq \
  && apt-get install clamav clamav-daemon clamdscan -y
```
now you can build the app by using `docker-compose build app`
and starting all the needed containers and you can test the command `clamscan` on your app container to get the scan results like:
```
----------- SCAN SUMMARY -----------
Known viruses: 0
Engine version: 0.101.5
Scanned directories: 0
Scanned files: 0
Infected files: 0
Data scanned: 0.00 MB
Data read: 0.00 MB (ratio 0.00:1)
Time: 0.002 sec (0 m 0 s)
```
and in `rails c` you can test it by using
```
[1] pry(main)> Clamby.safe?('public/images/astm.gif')
/app_path/public/images/astm.gif: OK
=> true
[2] pry(main)> Clamby.virus?('public/images/astm.gif')
/app_path/public/images/astm.gif: OK
=> false

```
